### PR TITLE
`parse_openapi_spec()` improvements

### LINKED ISSUE #186: parse_openapi_spec vs Asana
`yaml::read_yaml()` (invoked by `parse_openapi_spec()` via `read_spec()`) guesses some things incorrectly for the Asana API. This leads to it attempting to read something as int that isn't a single int, and everything failing.

``` r
api_spec_url <- "https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml"
api_spec_yaml_direct <- yaml::read_yaml(
  api_spec_url,
  # Some things are interpreted as ints but they aren't. For example, there
  # are pairs of ints that were being read in as ints, and then failing.
  handlers = list(int = as.character)
)

# Tibblify doesn't allow me to fix that.
api_spec_tibblify <- tibblify::parse_openapi_spec(api_spec_url)
#> Warning in yaml.load(string, error.label = error.label, ...): NAs introduced by
#> coercion: 521621,621373 is not an integer

#> Warning in yaml.load(string, error.label = error.label, ...): NAs introduced by
#> coercion: 521621,621373 is not an integer
#> Warning in yaml.load(string, error.label = error.label, ...): NAs introduced by
#> coercion: 5678904321 is out of integer range
#> Warning in yaml.load(string, error.label = error.label, ...): NAs introduced by
#> coercion: 4578152156 is out of integer range
#> Error in yaml.load(string, error.label = error.label, ...): (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml) Duplicate map key: 'NA'
```

<sup>Created on 2023-07-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I tried adding `...` arguments to `parse_openapi_spec` and `read_spec` to pass along to `read_yaml`, but that just pushed the error further downstream, without fixing:

```
[main 09:44:33] > api_spec_tibblify <- parse_openapi_spec(api_spec_url, handlers = list(int = as.character))
Error in `map2()`:
ℹ In index: 1.
ℹ With name: /attachments/{attachment_gid}.
Caused by error in `map2()`:
ℹ In index: 1.
ℹ With name: get.
Caused by error in `purrr::map()` at tibblify/R/parse-open-api.R:130:2:
ℹ In index: 1.
ℹ With name: 200.
Caused by error in `purrr::map()` at tibblify/R/parse-open-api.R:137:2:
ℹ In index: 1.
ℹ With name: application/json.
Caused by error in `map2()`:
ℹ In index: 1.
ℹ With name: data.
Caused by error in `handle_all_of()` at tibblify/R/parse-open-api.R:238:4:
! Can't combine tibs `..1` <variant> and `..2` <row>
Run `rlang::last_trace()` to see where the error occurred.
```
 
I'm in the process of basically rewriting this same function/set of functions, though, so it makes sense to keep working on fixing this/dealing with exceptions like this. I'll dig into the `parse_openapi_spec()` code further to see if it makes sense to keep this inside tibblify, or if it belongs outside (I think it's going to grow and grow to handle exceptions, which is why I lean toward it probably being something that *uses* tibblify over something that's *inside* tibblify, assuming tibblify still has a role once the exceptions are handled).

Let me know what you think!

### PR DESCRIPTION
**Pull request by mgirlich**
Fixes #186.

Now the three specs that failed all work:

```r
asana_yaml <- yaml::read_yaml("https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml", handlers = list(int = as.character))
asana_spec <- parse_openapi_spec(asana_yaml)

zoom_yaml <- yaml::read_yaml("https://api.apis.guru/v2/specs/zoom.us/2.0.0/openapi.yaml", handlers = list(int = as.character))
zoom_spec <- parse_openapi_spec(zoom_yaml)

youtube_yaml <- yaml::read_yaml("https://api.apis.guru/v2/specs/googleapis.com/youtube/v3/openapi.yaml")
youtube_spec <- parse_openapi_spec(youtube_yaml)
```

~While this can now be parsed, the performance could be improved.~ After some minor changes the performance is quite okay.

### CODE REVIEW

**Comment by jonthegeek** [comment]
Amazing, thank you! This appears to work great!

How would you feel about including the rest of the information in the spec (perhaps subject to arguments in parse_openapi_spec)? You're parsing the returns, which is definitely useful, but I'd like to also get the arguments, descriptions, etc.

At a minimum I'll be building off what you have (and using tibblify as the format for including specifications about what to expect), but it'd be helpful if it were built in completely.

**Comment by mgirlich** [comment]
I'm not quite sure. It kind of makes sense as this might be quite easy to integrate. On the other hand, this doesn't really fit to tibblify. I'll have a look into this to get a better feeling for the whole issue.

**Comment by jonthegeek** [comment]
To be clear, I just want to include everything that fits into that tibble; to add the missing columns from the incoming spec. I'm not sure why that wouldn't fit in tibblify.

**Comment by mgirlich** [comment]
@jonthegeek I added a PR #191 that parses more fields of the Open API spec. Does that help you or do you already have a parser by now?

**Comment by jonthegeek** [comment]
Yeah, this looks great... but I don't think it makes sense for tibblify to cover what I'm looking for. Keep an eye on [{rapid}](https://jonthegeek.github.io/rapid/) for my R API Definition package, which will HOPEFULLY have a v0.1 in the next couple days (or at least a PR with the basic idea laid out).

**Pull request merged**
