### PR TITLE
Replace PROTECT() and UNPROTECT() with cpp11 protection

### PR DESCRIPTION
**Pull request by krlmlr**
as the former are undefined across function boundaries.

This is the largest and messiest PR from #51 (but also difficult to disentangle), I'll double-check if it's necessary to weed out the protection errors.

### CODE REVIEW

**Comment by krlmlr** [comment]
@mgirlich: This is now as simple as it gets.

**Comment by mgirlich** [comment]
Thanks a lot.

At some point I used cpp11 but it seems I messed up something there because the performance was absolutely terrible (it took at least 10 times as long...). It seems this is not the case here so I am happy to use cpp11 in more places.

**Comment by krlmlr** [comment]
cpp11 protection works in constant time per protect/unprotect call. Do you have a dataset that we can use for measuring and profiling?

**Comment by mgirlich** [comment]
For now we could simply use some of the example JSON files from rcppsimdjson:

```r
base_path <- "https://raw.githubusercontent.com/eddelbuettel/rcppsimdjson/master/inst/jsonexamples/"

apache_list <- jsonlite::fromJSON(paste0(base_path, "apache_builds.json"), simplifyDataFrame = FALSE) %>% 
  list() %>% 
  rep(100)

apache_spec <- spec_df(
  assignedLabels = tib_list(
    "assignedLabels",
    transform = function (x)
    new_list_of(x = x, ptype = list())
  ),
  mode = tib_chr("mode"),
  nodeDescription = tib_chr("nodeDescription"),
  nodeName = tib_chr("nodeName"),
  numExecutors = tib_int("numExecutors"),
  description = tib_chr("description"),
  jobs = tib_df(
    "jobs",
    name = tib_chr("name"),
    url = tib_chr("url"),
    color = tib_chr("color")
  ),
  overallLoad = tib_unspecified("overallLoad"),
  primaryView = tib_row(
    "primaryView",
    name = tib_chr("name"),
    url = tib_chr("url")
  ),
  quietingDown = tib_lgl("quietingDown"),
  slaveAgentPort = tib_int("slaveAgentPort"),
  unlabeledLoad = tib_unspecified("unlabeledLoad"),
  useCrumbs = tib_lgl("useCrumbs"),
  useSecurity = tib_lgl("useSecurity"),
  views = tib_df(
    "views",
    name = tib_chr("name"),
    url = tib_chr("url")
  )
)

random_list <- jsonlite::fromJSON(paste0(base_path, "random.json"), simplifyDataFrame = FALSE) %>% 
  list() %>% 
  rep(100)
random_spec <- spec_df(
  id = tib_int("id"),
  jsonrpc = tib_chr("jsonrpc"),
  total = tib_int("total"),
  result = tib_df(
    "result",
    id = tib_int("id"),
    avatar = tib_chr("avatar"),
    age = tib_int("age"),
    admin = tib_lgl("admin"),
    name = tib_chr("name"),
    company = tib_chr("company"),
    phone = tib_chr("phone"),
    email = tib_chr("email"),
    birthDate = tib_chr("birthDate"),
    friends = tib_df(
      "friends",
      id = tib_int("id"),
      name = tib_chr("name"),
      phone = tib_chr("phone")
    ),
    field = tib_chr("field")
  )
)

(timings <- bench::mark(
  apache = tibblify(apache_list, apache_spec),
  random = tibblify(random_list, random_spec),
  check = FALSE,
  min_iterations = 5
))
#> # A tibble: 2 × 13
#>   expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm>
#> 1 apache       36.8ms   38.2ms     25.7     2.03MB     2.85     9     1   350.84ms
#> 2 random      430.4ms  440.7ms      2.25    7.32MB     0        5     0      2.22s
```

**Pull request merged**
